(()=>{'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>'<svg aria-hidden="true"><use href="#i-'+n+'"/></svg>';
let user=null,gallery=[],filter='all';
const read=(name,fallback)=>{try{return JSON.parse(localStorage.getItem('picgift.ui.'+(user?.id||'guest')+'.'+name))||fallback}catch{return fallback}};
const write=(name,value)=>{try{localStorage.setItem('picgift.ui.'+(user?.id||'guest')+'.'+name,JSON.stringify(value))}catch{}};
const notice=message=>{const e=$('toast');e.textContent=message;e.classList.add('on');clearTimeout(notice.timer);notice.timer=setTimeout(()=>e.classList.remove('on'),4200)};
const cards=(items)=>items.map(([name,image,action])=>'<button type="button" class="inspiration-card" '+action+'><img src="./assets/halloween/'+image+'" alt="'+esc(name)+'" loading="lazy"><span>'+esc(name)+'</span></button>').join('');
$('inspiration-scenes').innerHTML=cards([
 ['Bosque de calabazas','samples/calabazas.webp','data-select="reference-pumpkin-forest"'],['Castillo embrujado','reference/haunted-castle.webp','data-select="reference-haunted-castle"'],['Salón de retratos','reference/portrait-hall.webp','data-select="reference-portrait-hall"'],['Ciudad encantada','reference/enchanted-city.webp','data-select="reference-enchanted-city"']]);
$('inspiration-poses').innerHTML=cards([
 ['Sentado con calabazas','samples/calabazas.webp','data-pose-idea="Sentado en el banco" data-scene-idea="halloween-pumpkin-bench"'],['De pie','samples/bosque.webp','data-pose-idea="De pie" data-scene-idea="halloween-autumn-arch"'],['Preparando pociones','samples/pociones.webp','data-pose-idea="De pie tras el caldero" data-scene-idea="halloween-potions"'],['Una postura natural','guide/sentado.webp','data-panel="tips"']]);
$('inspiration-outfits').innerHTML=cards([
 ['Disfraz de bruja','samples/bosque.webp','data-outfit-idea="Brujita de cuento"'],['Pequeños magos','samples/pociones.webp','data-outfit-idea="Pequeño mago"'],['Entre calabazas','samples/calabazas.webp','data-outfit-idea="Automático para la escena"'],['Tu propio estilo','journey/result.webp','data-outfit-idea="Conservar ropa original"']]);
$('inspiration-tips').innerHTML=cards([
 ['Cuerpo entero','guide/cuerpo-entero.webp','data-panel="tips"'],['Rostro nítido','guide/retrato.webp','data-panel="tips"'],['Postura natural','guide/sentado.webp','data-panel="tips"'],['Qué evitar','guide/evitar.webp','data-panel="tips"']]);
const setInspiration=key=>{document.querySelectorAll('[data-inspiration-tabs]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.inspirationTabs===key));document.querySelectorAll('[data-inspiration-section]').forEach(s=>s.hidden=key==='all'?s.dataset.inspirationSection==='tips':s.dataset.inspirationSection!==key)};
const galleryCard=(o,small=false)=>{const j=o.job,name=o.name||'PICGIFT',favorite=read('favorites',[]).includes(j.id),ready=j.status==='completed'&&o.href;
 return '<article class="photo-card'+(small?' photo-card--small':'')+'" data-gallery-job="'+esc(j.id)+'"><div class="photo-card-art">'+(ready?'<button class="photo-open" type="button" data-view-job="'+esc(j.id)+'" aria-label="Ver '+esc(name)+'"><img src="'+esc(o.href)+'" alt="Tu retrato '+esc(name)+'" loading="lazy"></button>':'<div class="photo-pending">'+icon('spark')+'<span>'+esc(o.statusLabel||j.status)+'</span></div>')+(!small?'<button class="photo-menu-toggle" type="button" data-photo-menu="'+esc(j.id)+'" aria-expanded="false" aria-label="Opciones del retrato">•••</button><div class="photo-menu" data-menu-for="'+esc(j.id)+'" hidden><button type="button" data-view-job="'+esc(j.id)+'">Ver estado y detalles</button><button type="button" data-report-job="'+esc(j.id)+'">Informar de un problema</button><button type="button" data-delete-job="'+esc(j.id)+'">Eliminar fotografía</button></div><span class="photo-status '+(ready?'ready':'processing')+'">'+(ready?'Lista':esc(o.statusLabel||'En proceso'))+'</span>':'<button class="photo-favorite" type="button" data-favorite-job="'+esc(j.id)+'" aria-pressed="'+favorite+'" aria-label="'+(favorite?'Quitar de favoritas':'Añadir a favoritas')+'">'+icon('heart')+'</button>')+'</div><div class="photo-card-info"><h3>'+esc(name)+'</h3><p>'+esc(new Date(j.created_at).toLocaleDateString('es-ES',{day:'numeric',month:'short',year:'numeric'}))+'</p></div>'+(!small?'<div class="photo-actions">'+(ready?'<a href="'+esc(o.download||o.href)+'" rel="noopener noreferrer" aria-label="Descargar retrato">'+icon('download')+'</a><button type="button" data-share-job="'+esc(j.id)+'" aria-label="Compartir retrato">'+icon('share')+'</button>':'<button type="button" disabled aria-label="Descarga todavía no disponible">'+icon('download')+'</button><button type="button" disabled aria-label="Compartir todavía no disponible">'+icon('share')+'</button>')+'<button type="button" data-favorite-job="'+esc(j.id)+'" aria-pressed="'+favorite+'" aria-label="'+(favorite?'Quitar de favoritas':'Añadir a favoritas')+'">'+icon('heart')+'</button></div>':'')+'</article>';
};
function stats(){const favorites=read('favorites',[]);$('profile-photo-count').textContent=gallery.filter(o=>o.job.status==='completed').length;$('profile-favorite-count').textContent=gallery.filter(o=>favorites.includes(o.job.id)).length;$('profile-scene-count').textContent=read('explored',[]).length;}
function renderGallery(){
 if(!user)return;
 const list=filter==='favorites'?gallery.filter(o=>read('favorites',[]).includes(o.job.id)):filter==='deleted'?[]:gallery;
 const empty=filter==='deleted'?'Las fotografías eliminadas se borran definitivamente de tu espacio privado.':filter==='favorites'?'Marca el corazón de un retrato para guardarlo aquí.':'Tu primera fotografía aparecerá aquí después de generarla.';
 $('photo-library').innerHTML=list.length?'<div class="app-section-head"><h2>Fotos recientes</h2><button type="button" data-all-photos>Ver todas ›</button></div><div class="recent-photo-grid">'+list.slice(0,3).map(o=>galleryCard(o)).join('')+'</div><div class="app-section-head all-photos-heading"><h2>Todas mis fotos</h2><button type="button" data-sort-photos>Ordenar ⌄</button></div><div class="all-photo-grid">'+list.map(o=>galleryCard(o,true)).join('')+'</div>':'<div class="panel empty"><div class="large">'+icon('gallery')+'</div><h3>'+(filter==='deleted'?'No conservamos fotos eliminadas':filter==='favorites'?'Tus favoritas':'Todavía no hay fotografías')+'</h3><p>'+empty+'</p><button class="btn outline" type="button" data-route="crear">Crear nueva foto</button></div>';
 stats();
}
window.picgiftRenderGallery=items=>{gallery=items;renderGallery()};
function profile(){const preferences=read('preferences',{});$('photo-email-delivery').checked=!!preferences.email;if(preferences.outfit)$('outfit').value=preferences.outfit;const name=user?.user_metadata?.display_name||user?.user_metadata?.full_name||user?.email?.split('@')[0]||'Mi cuenta';$('profile-name').textContent=name;const avatar=$('account-avatar');avatar.textContent=name.slice(0,1).toUpperCase();const url=user?.user_metadata?.avatar_url;if(url){try{const parsed=new URL(url);if(parsed.protocol==='https:'){const img=new Image();img.src=parsed.href;img.alt='Foto de perfil';img.referrerPolicy='no-referrer';avatar.replaceChildren(img)}}catch{}}stats();}
window.addEventListener('picgift:auth',e=>{user=e.detail.user||null;gallery=[];filter='all';profile();if(!user)return;renderGallery();});
window.addEventListener('picgift:profile-updated',e=>{if(e.detail.user){user=e.detail.user;profile()}if(e.detail.error){$('profile-save-status').textContent=e.detail.error;return}if(e.detail.user){$('app-panel').close();notice('Perfil actualizado.')}});
const dialog=$('app-panel');
function panel(key){
 const content=$('app-panel-content'),prefs=read('preferences',{});
 if(key==='edit'){content.innerHTML='<h2>Editar perfil</h2><form id="profile-edit-form"><label class="field"><span>Nombre</span><input id="profile-display-name" maxlength="60" required value="'+esc($('profile-name').textContent)+'"></label><p id="profile-save-status" role="status"></p><button class="btn primary" type="submit">Guardar nombre</button></form>';}
 else if(key==='account'){content.innerHTML='<h2>Información de la cuenta</h2><p>'+esc(user?.email||'Inicia sesión para acceder a tu cuenta.')+'</p><p>Temporada activa: Halloween 2026</p><button class="btn outline" type="button" data-panel="edit">Editar nombre</button><a class="text-btn" href="./delete-account.html">Solicitar eliminación de cuenta</a>';}
 else if(key==='privacy'){content.innerHTML='<h2>Privacidad y seguridad</h2><p>La vista previa se prepara en tu dispositivo. La fotografía se envía al servidor cuando autorizas e inicias la creación.</p><p>Los retratos de tu galería usan enlaces privados temporales. Puedes eliminar cada fotografía desde su menú.</p><button class="btn outline" type="button" data-password-setup>Crear o cambiar mi contraseña</button><p>Puedes entrar con tu correo y contraseña aunque tu cuenta se haya creado con Google.</p><a class="btn outline" href="./privacy.html">Leer política de privacidad</a>';}
 else if(key==='notifications'){content.innerHTML='<h2>Notificaciones</h2><p>Controla los avisos que quieres recibir en este dispositivo.</p><label class="check"><input type="checkbox" data-preference="email" '+(prefs.email?'checked':'')+'> Activar por defecto el aviso por correo en este dispositivo</label>'+(window.PicgiftNative?'<label class="check"><input type="checkbox" id="picgift-push-consent"> Recibir avisos de novedades y promociones en mi móvil</label><p id="picgift-push-status" role="status" aria-live="polite">Consultando notificaciones…</p>':'<p>Las notificaciones del móvil están disponibles en la aplicación Android de PICGIFT.</p>');if(window.PicgiftNative)window.dispatchEvent(new Event('picgift:push-panel'));}
 else if(key==='style'){content.innerHTML='<h2>Preferencias de estilo</h2><p>Tu vestuario preferido para futuras fotos en este dispositivo.</p><select id="preferred-outfit">'+['Automático para la escena','Brujita de cuento','Pequeño mago','Conservar ropa original'].map(v=>'<option '+(prefs.outfit===v?'selected':'')+'>'+v+'</option>').join('')+'</select>';}
 else if(key==='tips'){content.innerHTML='<h2>Consejos para tu foto</h2><p>Elige una foto nítida, con buena luz, la cabeza recta y el cuerpo completo. Evita filtros, contraluz y rostros tapados.</p><div class="panel-guide"><img src="./assets/halloween/guide/cuerpo-entero.webp" alt="Ejemplo de cuerpo completo"><img src="./assets/halloween/guide/retrato.webp" alt="Ejemplo de rostro nítido"></div><p>JPG, PNG o WEBP · Máximo 15 MB.</p>';}
 else {content.innerHTML='<h2>Ayuda y soporte</h2><details open><summary>¿Cómo creo mi foto?</summary><p>Sube una foto, elige un decorado disponible, inicia sesión y acepta la autorización antes de crear.</p></details><details><summary>¿Dónde está mi resultado?</summary><p>Abre Mis fotos para consultar su estado. La descarga estará disponible cuando termine.</p></details><details><summary>¿Cómo informo de un problema?</summary><p>En Mis fotos, abre el menú de tu retrato y selecciona «Informar de un problema».</p></details><a class="text-btn" href="./privacy.html">Privacidad y contacto</a>';}
 if(!dialog.open)dialog.showModal();
}
document.addEventListener('click',async e=>{
 if(e.target.closest('[data-upload-change]')){$('photo').click();return}
 const panelButton=e.target.closest('[data-panel]');if(panelButton){panel(panelButton.dataset.panel);return}
 if(e.target.closest('.panel-close')){dialog.close();return}
 const tab=e.target.closest('[data-inspiration-tabs]');if(tab)setInspiration(tab.dataset.inspirationTabs);
 const show=e.target.closest('[data-show-inspiration]');if(show)setInspiration(show.dataset.showInspiration);
 const galleryTab=e.target.closest('[data-gallery-tabs]');if(galleryTab){filter=galleryTab.dataset.galleryTabs;document.querySelectorAll('[data-gallery-tabs]').forEach(b=>b.setAttribute('aria-pressed',b===galleryTab));renderGallery()}
 const favorite=e.target.closest('[data-favorite-job]');if(favorite){const id=favorite.dataset.favoriteJob,current=read('favorites',[]);write('favorites',current.includes(id)?current.filter(v=>v!==id):[...current,id]);renderGallery()}
 const menu=e.target.closest('[data-photo-menu]');if(menu){const target=menu.parentElement.querySelector('.photo-menu');target.hidden=!target.hidden;menu.setAttribute('aria-expanded',!target.hidden)}
 if(e.target.closest('[data-sort-photos]')){gallery.reverse();renderGallery()}
 if(e.target.closest('[data-all-photos]'))document.querySelector('.all-photos-heading')?.scrollIntoView({behavior:'smooth'});
 if(e.target.closest('[data-open-favorites]')){window.dispatchEvent(new CustomEvent('picgift:route',{detail:{name:'mis-fotos'}}));filter='favorites';document.querySelectorAll('[data-gallery-tabs]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.galleryTabs==='favorites'));renderGallery()}
 const share=e.target.closest('[data-share-job]');if(share){const o=gallery.find(v=>v.job.id===share.dataset.shareJob);if(!o?.href)return;try{if(navigator.share)await navigator.share({title:'Mi retrato PICGIFT',url:o.href});else{await navigator.clipboard.writeText(o.href);notice('Enlace privado copiado. Caduca en una hora.')}}catch(err){if(err.name!=='AbortError')notice('No se pudo compartir. Puedes descargar la foto.')}}
 const selected=e.target.closest('[data-select]');if(selected){const id=selected.dataset.select,seen=read('explored',[]);if(!seen.includes(id))write('explored',[...seen,id]);stats()}
 const outfit=e.target.closest('[data-outfit-idea]');if(outfit){window.dispatchEvent(new CustomEvent('picgift:route',{detail:{name:'crear'}}));$('outfit').value=outfit.dataset.outfitIdea;$('studio-advanced').open=true;notice('Vestuario seleccionado. Sube tu fotografía para continuar.')}
 const pose=e.target.closest('[data-pose-idea]');if(pose){document.querySelector('[data-select="'+pose.dataset.sceneIdea+'"]')?.click();$('pose').value=pose.dataset.poseIdea;notice('Pose y decorado seleccionados.')}
});
dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close()}});
document.addEventListener('change',e=>{if(e.target.matches('[data-preference],#preferred-outfit')){const prefs=read('preferences',{});if(e.target.id==='preferred-outfit'){prefs.outfit=e.target.value;$('outfit').value=e.target.value}else{prefs.email=e.target.checked;$('photo-email-delivery').checked=e.target.checked}write('preferences',prefs);notice('Preferencia guardada en este dispositivo.')}});
document.addEventListener('submit',e=>{if(e.target.id==='profile-edit-form'){e.preventDefault();$('profile-save-status').textContent='Guardando…';window.dispatchEvent(new CustomEvent('picgift:update-profile',{detail:{display_name:$('profile-display-name').value.trim()}}))}});
if(window.picgiftCurrentUser){user=window.picgiftCurrentUser;gallery=window.picgiftGallery||[];profile();renderGallery();}
})();
