const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.PICGIFT_UI_ARTIFACTS||'artifacts/mobile-welcome');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png'};
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]||'/'));const file=p===root?path.join(root,'index.html'):p;if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(b)});});
const mock=`export function createClient(){const user={id:'11111111-1111-1111-1111-111111111111',email:'admin@example.test',user_metadata:{full_name:'Admin',picgift_password_backup:true}};return {auth:{getSession:async()=>({data:{session:{user}}}),getUser:async()=>({data:{user}}),onAuthStateChange(fn){setTimeout(()=>fn('INITIAL_SESSION',{user}),100)},signOut:async()=>({}),updateUser:async()=>({data:{user}})},functions:{invoke:async(name,{body})=>{if(name==='picgift-admin')return {data:body.action==='health'?{admin:window.testAdmin!==false}:{admin:true,users:[],settings:{global_daily_limit:48,default_user_daily_limit:3},premium_settings:{daily_limit:3},global_used:0,utc_day:'2026-10-10'}};if(name==='picgift-ai-director')return {data:{providers:{free_configured:true,premium_configured:true},pending:1,proposals:[{id:'example',kind:'scene',status:'pending',title:'Propuesta de prueba',created_at:new Date().toISOString(),description:'Escenario ficticio para validar la interfaz.',category:'Halloween',preview_url:'/assets/halloween/reference/moon-castle.webp'}],outbox:[]}};if(name==='picgift-notifications')return {data:{configured:true,devices:0,history:[]}};return {data:{}}}},from(){return {select(){return this},eq(){return this},order(){return this},limit(){return this},maybeSingle:async()=>({data:null}),then(resolve){return Promise.resolve({data:[]}).then(resolve)}}}}}`;
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(8133,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,locale:'es-ES'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route(/^https?:\/\/(?!127\.0\.0\.1)/,r=>r.request().url().startsWith('https://esm.sh/@supabase/supabase-js@')?r.fulfill({contentType:'text/javascript',body:mock}):r.abort());
await page.addInitScript(()=>{localStorage.setItem('picgift.language','es');window.nativeRequests=[];window.PicgiftNative={postMessage:message=>window.nativeRequests.push(JSON.parse(message))};window.picgiftNativeGoogleSupported=true});
await page.goto('http://127.0.0.1:8133/#crear');await page.waitForSelector('#first-steps[open]');await page.screenshot({path:path.join(out,'01-primeros-pasos.png')});assert.equal((await page.evaluate(()=>window.nativeRequests)).filter(x=>x.action==='notifications-enable').length,0);
await page.getByRole('button',{name:'Empezar mi foto',exact:true}).click();await page.waitForFunction(()=>window.nativeRequests.some(x=>x.action==='notifications-enable'));await page.waitForTimeout(1600);assert.equal((await page.evaluate(()=>window.nativeRequests)).filter(x=>x.action==='notifications-enable').length,1);assert.equal(await page.locator('#mobile-signin').isVisible(),false);await page.screenshot({path:path.join(out,'02-bienvenida.png')});
await page.reload();await page.waitForTimeout(900);assert.equal(await page.locator('#first-steps').evaluate(e=>e.open),false);assert.equal((await page.evaluate(()=>window.nativeRequests)).filter(x=>x.action==='notifications-enable').length,0);
await page.evaluate(()=>window.dispatchEvent(new CustomEvent('picgift:native-push',{detail:{status:'permission_denied'}})));await page.reload();await page.waitForTimeout(900);assert.equal((await page.evaluate(()=>window.nativeRequests)).filter(x=>x.action==='notifications-enable').length,0);
await page.locator('.mobile-nav [data-route="cuenta"]').click();await page.waitForSelector('#admin-dashboard-link:visible');await page.locator('#admin-dashboard-link').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'03-perfil-admin.png')});await page.locator('#admin-dashboard-link').click();await page.waitForSelector('#dashboard:not([hidden])');await page.waitForSelector('#ai-director-list article');assert.equal(await page.getByRole('heading',{name:'Disponible solo en la web'}).count(),0);await page.locator('#ai-director-section').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'04-admin-movil.png'),fullPage:false});
for(const width of [320,390,768]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Admin overflows at '+width)}
await page.goto('http://127.0.0.1:8133/#crear');await page.setViewportSize({width:390,height:844});await page.waitForTimeout(700);await page.evaluate(()=>window.dispatchEvent(new CustomEvent('picgift:auth',{detail:{user:null}})));await page.waitForSelector('#mobile-signin:visible');assert.ok((await page.locator('#mobile-signin .google-signin').boundingBox()).width<=240);await page.screenshot({path:path.join(out,'05-google-compacto.png')});
await page.addInitScript(()=>window.testAdmin=false);await page.goto('http://127.0.0.1:8133/admin.html');await page.waitForSelector('#blocked-title');await page.waitForFunction(()=>document.getElementById('blocked-title').textContent==='Acceso no autorizado');assert.equal(await page.locator('#dashboard').isVisible(),false);assert.deepEqual(errors,[]);await browser.close();server.close();console.log('Verified: onboarding once, notification consent after onboarding, no reprompt after denial, native admin and responsive 320/390/768px, compact Google.');})().catch(e=>{console.error(e);server.close();process.exit(1)});
